steps:
    # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/a-ramen', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/a-ramen']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      [
        'beta', 
        'run', 
        'deploy', 
        'a-ramen', 
        '--image', 
        'gcr.io/$PROJECT_ID/a-ramen', 
        '--region',
        'asia-east1',
        '--platform', 
        'managed', 
        '--quiet']
#  - name: "gcr.io/cloud-builders/gcloud"
#    args:
#      [
#        "beta",
#        "run",
#        "services",
#        "update",
#        "a-ramen",
#        "--add-cloudsql-instances",
#        "tbc-linenext:asia-east1:tbc-linenext",
#        "--platform",
#        "managed",
#        "--region",
#        "asia-east1",
#        "--set-env-vars",
#        "CLOUD_SQL_CONNECTION_NAME=tbc-linenext:asia-east1:tbc-linenext,DB_USER=tbc-system,DB_PASS=pdzLblsLGFdO2yFK,DB_NAME=TBC-BigHelp-Dev"
#      ]
images:
  - gcr.io/$PROJECT_ID/a-ramen