// Code generated by ent, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldPhoneNumber holds the string denoting the phone_number field in the database.
	FieldPhoneNumber = "phone_number"
	// FieldBirthdate holds the string denoting the birthdate field in the database.
	FieldBirthdate = "birthdate"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldPoint holds the string denoting the point field in the database.
	FieldPoint = "point"
	// FieldStar holds the string denoting the star field in the database.
	FieldStar = "star"
	// EdgeOtp holds the string denoting the otp edge name in mutations.
	EdgeOtp = "otp"
	// EdgeQrcode holds the string denoting the qrcode edge name in mutations.
	EdgeQrcode = "qrcode"
	// Table holds the table name of the user in the database.
	Table = "users"
	// OtpTable is the table that holds the otp relation/edge.
	OtpTable = "user_otps"
	// OtpInverseTable is the table name for the UserOtp entity.
	// It exists in this package in order to avoid circular dependency with the "userotp" package.
	OtpInverseTable = "user_otps"
	// OtpColumn is the table column denoting the otp relation/edge.
	OtpColumn = "user_id"
	// QrcodeTable is the table that holds the qrcode relation/edge.
	QrcodeTable = "qrcodes"
	// QrcodeInverseTable is the table name for the Qrcode entity.
	// It exists in this package in order to avoid circular dependency with the "qrcode" package.
	QrcodeInverseTable = "qrcodes"
	// QrcodeColumn is the table column denoting the qrcode relation/edge.
	QrcodeColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldFirstName,
	FieldLastName,
	FieldPhoneNumber,
	FieldBirthdate,
	FieldEmail,
	FieldCreatedAt,
	FieldPoint,
	FieldStar,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
