// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Branches is the predicate function for branches builders.
type Branches func(*sql.Selector)

// News is the predicate function for news builders.
type News func(*sql.Selector)

// Qrcode is the predicate function for qrcode builders.
type Qrcode func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserOtp is the predicate function for userotp builders.
type UserOtp func(*sql.Selector)
