// Code generated by ent, DO NOT EDIT.

package news

const (
	// Label holds the string label denoting the news type in the database.
	Label = "news"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTag holds the string denoting the tag field in the database.
	FieldTag = "tag"
	// FieldPlace holds the string denoting the place field in the database.
	FieldPlace = "place"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// Table holds the table name of the news in the database.
	Table = "news"
)

// Columns holds all SQL columns for news fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldTag,
	FieldPlace,
	FieldDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
