// Code generated by ent, DO NOT EDIT.

package userotp

const (
	// Label holds the string label denoting the userotp type in the database.
	Label = "user_otp"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldReference holds the string denoting the reference field in the database.
	FieldReference = "reference"
	// FieldHashedOtp holds the string denoting the hashed_otp field in the database.
	FieldHashedOtp = "hashed_otp"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the userotp in the database.
	Table = "user_otps"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_otps"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for userotp fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldReference,
	FieldHashedOtp,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
