// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aramen-api/cmd/api/ent/branches"
	"aramen-api/cmd/api/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BranchesUpdate is the builder for updating Branches entities.
type BranchesUpdate struct {
	config
	hooks    []Hook
	mutation *BranchesMutation
}

// Where appends a list predicates to the BranchesUpdate builder.
func (bu *BranchesUpdate) Where(ps ...predicate.Branches) *BranchesUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetName sets the "name" field.
func (bu *BranchesUpdate) SetName(s string) *BranchesUpdate {
	bu.mutation.SetName(s)
	return bu
}

// SetShortDescription sets the "short_description" field.
func (bu *BranchesUpdate) SetShortDescription(s string) *BranchesUpdate {
	bu.mutation.SetShortDescription(s)
	return bu
}

// SetFullDescription sets the "full_description" field.
func (bu *BranchesUpdate) SetFullDescription(s string) *BranchesUpdate {
	bu.mutation.SetFullDescription(s)
	return bu
}

// SetTelephone sets the "telephone" field.
func (bu *BranchesUpdate) SetTelephone(s string) *BranchesUpdate {
	bu.mutation.SetTelephone(s)
	return bu
}

// SetLatitude sets the "latitude" field.
func (bu *BranchesUpdate) SetLatitude(i int) *BranchesUpdate {
	bu.mutation.ResetLatitude()
	bu.mutation.SetLatitude(i)
	return bu
}

// AddLatitude adds i to the "latitude" field.
func (bu *BranchesUpdate) AddLatitude(i int) *BranchesUpdate {
	bu.mutation.AddLatitude(i)
	return bu
}

// SetLongitude sets the "longitude" field.
func (bu *BranchesUpdate) SetLongitude(i int) *BranchesUpdate {
	bu.mutation.ResetLongitude()
	bu.mutation.SetLongitude(i)
	return bu
}

// AddLongitude adds i to the "longitude" field.
func (bu *BranchesUpdate) AddLongitude(i int) *BranchesUpdate {
	bu.mutation.AddLongitude(i)
	return bu
}

// SetGooleMapURL sets the "goole_map_url" field.
func (bu *BranchesUpdate) SetGooleMapURL(s string) *BranchesUpdate {
	bu.mutation.SetGooleMapURL(s)
	return bu
}

// SetDineIn sets the "dine_in" field.
func (bu *BranchesUpdate) SetDineIn(b bool) *BranchesUpdate {
	bu.mutation.SetDineIn(b)
	return bu
}

// SetDelivery sets the "delivery" field.
func (bu *BranchesUpdate) SetDelivery(b bool) *BranchesUpdate {
	bu.mutation.SetDelivery(b)
	return bu
}

// SetTakeAway sets the "take_away" field.
func (bu *BranchesUpdate) SetTakeAway(b bool) *BranchesUpdate {
	bu.mutation.SetTakeAway(b)
	return bu
}

// Mutation returns the BranchesMutation object of the builder.
func (bu *BranchesUpdate) Mutation() *BranchesMutation {
	return bu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BranchesUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bu.hooks) == 0 {
		affected, err = bu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BranchesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bu.mutation = mutation
			affected, err = bu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bu.hooks) - 1; i >= 0; i-- {
			if bu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BranchesUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BranchesUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BranchesUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BranchesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   branches.Table,
			Columns: branches.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: branches.FieldID,
			},
		},
	}
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: branches.FieldName,
		})
	}
	if value, ok := bu.mutation.ShortDescription(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: branches.FieldShortDescription,
		})
	}
	if value, ok := bu.mutation.FullDescription(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: branches.FieldFullDescription,
		})
	}
	if value, ok := bu.mutation.Telephone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: branches.FieldTelephone,
		})
	}
	if value, ok := bu.mutation.Latitude(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: branches.FieldLatitude,
		})
	}
	if value, ok := bu.mutation.AddedLatitude(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: branches.FieldLatitude,
		})
	}
	if value, ok := bu.mutation.Longitude(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: branches.FieldLongitude,
		})
	}
	if value, ok := bu.mutation.AddedLongitude(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: branches.FieldLongitude,
		})
	}
	if value, ok := bu.mutation.GooleMapURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: branches.FieldGooleMapURL,
		})
	}
	if value, ok := bu.mutation.DineIn(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: branches.FieldDineIn,
		})
	}
	if value, ok := bu.mutation.Delivery(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: branches.FieldDelivery,
		})
	}
	if value, ok := bu.mutation.TakeAway(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: branches.FieldTakeAway,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{branches.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// BranchesUpdateOne is the builder for updating a single Branches entity.
type BranchesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BranchesMutation
}

// SetName sets the "name" field.
func (buo *BranchesUpdateOne) SetName(s string) *BranchesUpdateOne {
	buo.mutation.SetName(s)
	return buo
}

// SetShortDescription sets the "short_description" field.
func (buo *BranchesUpdateOne) SetShortDescription(s string) *BranchesUpdateOne {
	buo.mutation.SetShortDescription(s)
	return buo
}

// SetFullDescription sets the "full_description" field.
func (buo *BranchesUpdateOne) SetFullDescription(s string) *BranchesUpdateOne {
	buo.mutation.SetFullDescription(s)
	return buo
}

// SetTelephone sets the "telephone" field.
func (buo *BranchesUpdateOne) SetTelephone(s string) *BranchesUpdateOne {
	buo.mutation.SetTelephone(s)
	return buo
}

// SetLatitude sets the "latitude" field.
func (buo *BranchesUpdateOne) SetLatitude(i int) *BranchesUpdateOne {
	buo.mutation.ResetLatitude()
	buo.mutation.SetLatitude(i)
	return buo
}

// AddLatitude adds i to the "latitude" field.
func (buo *BranchesUpdateOne) AddLatitude(i int) *BranchesUpdateOne {
	buo.mutation.AddLatitude(i)
	return buo
}

// SetLongitude sets the "longitude" field.
func (buo *BranchesUpdateOne) SetLongitude(i int) *BranchesUpdateOne {
	buo.mutation.ResetLongitude()
	buo.mutation.SetLongitude(i)
	return buo
}

// AddLongitude adds i to the "longitude" field.
func (buo *BranchesUpdateOne) AddLongitude(i int) *BranchesUpdateOne {
	buo.mutation.AddLongitude(i)
	return buo
}

// SetGooleMapURL sets the "goole_map_url" field.
func (buo *BranchesUpdateOne) SetGooleMapURL(s string) *BranchesUpdateOne {
	buo.mutation.SetGooleMapURL(s)
	return buo
}

// SetDineIn sets the "dine_in" field.
func (buo *BranchesUpdateOne) SetDineIn(b bool) *BranchesUpdateOne {
	buo.mutation.SetDineIn(b)
	return buo
}

// SetDelivery sets the "delivery" field.
func (buo *BranchesUpdateOne) SetDelivery(b bool) *BranchesUpdateOne {
	buo.mutation.SetDelivery(b)
	return buo
}

// SetTakeAway sets the "take_away" field.
func (buo *BranchesUpdateOne) SetTakeAway(b bool) *BranchesUpdateOne {
	buo.mutation.SetTakeAway(b)
	return buo
}

// Mutation returns the BranchesMutation object of the builder.
func (buo *BranchesUpdateOne) Mutation() *BranchesMutation {
	return buo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BranchesUpdateOne) Select(field string, fields ...string) *BranchesUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Branches entity.
func (buo *BranchesUpdateOne) Save(ctx context.Context) (*Branches, error) {
	var (
		err  error
		node *Branches
	)
	if len(buo.hooks) == 0 {
		node, err = buo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BranchesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			buo.mutation = mutation
			node, err = buo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(buo.hooks) - 1; i >= 0; i-- {
			if buo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = buo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, buo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Branches)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from BranchesMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BranchesUpdateOne) SaveX(ctx context.Context) *Branches {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BranchesUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BranchesUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BranchesUpdateOne) sqlSave(ctx context.Context) (_node *Branches, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   branches.Table,
			Columns: branches.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: branches.FieldID,
			},
		},
	}
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Branches.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, branches.FieldID)
		for _, f := range fields {
			if !branches.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != branches.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: branches.FieldName,
		})
	}
	if value, ok := buo.mutation.ShortDescription(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: branches.FieldShortDescription,
		})
	}
	if value, ok := buo.mutation.FullDescription(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: branches.FieldFullDescription,
		})
	}
	if value, ok := buo.mutation.Telephone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: branches.FieldTelephone,
		})
	}
	if value, ok := buo.mutation.Latitude(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: branches.FieldLatitude,
		})
	}
	if value, ok := buo.mutation.AddedLatitude(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: branches.FieldLatitude,
		})
	}
	if value, ok := buo.mutation.Longitude(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: branches.FieldLongitude,
		})
	}
	if value, ok := buo.mutation.AddedLongitude(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: branches.FieldLongitude,
		})
	}
	if value, ok := buo.mutation.GooleMapURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: branches.FieldGooleMapURL,
		})
	}
	if value, ok := buo.mutation.DineIn(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: branches.FieldDineIn,
		})
	}
	if value, ok := buo.mutation.Delivery(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: branches.FieldDelivery,
		})
	}
	if value, ok := buo.mutation.TakeAway(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: branches.FieldTakeAway,
		})
	}
	_node = &Branches{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{branches.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
