// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aramen-api/cmd/api/ent/predicate"
	"aramen-api/cmd/api/ent/qrcode"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QrcodeDelete is the builder for deleting a Qrcode entity.
type QrcodeDelete struct {
	config
	hooks    []Hook
	mutation *QrcodeMutation
}

// Where appends a list predicates to the QrcodeDelete builder.
func (qd *QrcodeDelete) Where(ps ...predicate.Qrcode) *QrcodeDelete {
	qd.mutation.Where(ps...)
	return qd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (qd *QrcodeDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(qd.hooks) == 0 {
		affected, err = qd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QrcodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			qd.mutation = mutation
			affected, err = qd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(qd.hooks) - 1; i >= 0; i-- {
			if qd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = qd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, qd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (qd *QrcodeDelete) ExecX(ctx context.Context) int {
	n, err := qd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (qd *QrcodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: qrcode.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: qrcode.FieldID,
			},
		},
	}
	if ps := qd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, qd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// QrcodeDeleteOne is the builder for deleting a single Qrcode entity.
type QrcodeDeleteOne struct {
	qd *QrcodeDelete
}

// Exec executes the deletion query.
func (qdo *QrcodeDeleteOne) Exec(ctx context.Context) error {
	n, err := qdo.qd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{qrcode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (qdo *QrcodeDeleteOne) ExecX(ctx context.Context) {
	qdo.qd.ExecX(ctx)
}
