// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aramen-api/cmd/api/ent/predicate"
	"aramen-api/cmd/api/ent/qrcode"
	"aramen-api/cmd/api/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QrcodeUpdate is the builder for updating Qrcode entities.
type QrcodeUpdate struct {
	config
	hooks    []Hook
	mutation *QrcodeMutation
}

// Where appends a list predicates to the QrcodeUpdate builder.
func (qu *QrcodeUpdate) Where(ps ...predicate.Qrcode) *QrcodeUpdate {
	qu.mutation.Where(ps...)
	return qu
}

// SetQrcodeID sets the "qrcode_id" field.
func (qu *QrcodeUpdate) SetQrcodeID(s string) *QrcodeUpdate {
	qu.mutation.SetQrcodeID(s)
	return qu
}

// SetOrderID sets the "order_id" field.
func (qu *QrcodeUpdate) SetOrderID(s string) *QrcodeUpdate {
	qu.mutation.SetOrderID(s)
	return qu
}

// SetOrderStatus sets the "order_status" field.
func (qu *QrcodeUpdate) SetOrderStatus(s string) *QrcodeUpdate {
	qu.mutation.SetOrderStatus(s)
	return qu
}

// SetBranchName sets the "branch_name" field.
func (qu *QrcodeUpdate) SetBranchName(s string) *QrcodeUpdate {
	qu.mutation.SetBranchName(s)
	return qu
}

// SetOrderChannel sets the "order_channel" field.
func (qu *QrcodeUpdate) SetOrderChannel(s string) *QrcodeUpdate {
	qu.mutation.SetOrderChannel(s)
	return qu
}

// SetTotalPaid sets the "total_paid" field.
func (qu *QrcodeUpdate) SetTotalPaid(i int) *QrcodeUpdate {
	qu.mutation.ResetTotalPaid()
	qu.mutation.SetTotalPaid(i)
	return qu
}

// AddTotalPaid adds i to the "total_paid" field.
func (qu *QrcodeUpdate) AddTotalPaid(i int) *QrcodeUpdate {
	qu.mutation.AddTotalPaid(i)
	return qu
}

// SetUserID sets the "user_id" field.
func (qu *QrcodeUpdate) SetUserID(i int) *QrcodeUpdate {
	qu.mutation.SetUserID(i)
	return qu
}

// SetUser sets the "user" edge to the User entity.
func (qu *QrcodeUpdate) SetUser(u *User) *QrcodeUpdate {
	return qu.SetUserID(u.ID)
}

// Mutation returns the QrcodeMutation object of the builder.
func (qu *QrcodeUpdate) Mutation() *QrcodeMutation {
	return qu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (qu *QrcodeUpdate) ClearUser() *QrcodeUpdate {
	qu.mutation.ClearUser()
	return qu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (qu *QrcodeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(qu.hooks) == 0 {
		if err = qu.check(); err != nil {
			return 0, err
		}
		affected, err = qu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QrcodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = qu.check(); err != nil {
				return 0, err
			}
			qu.mutation = mutation
			affected, err = qu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(qu.hooks) - 1; i >= 0; i-- {
			if qu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = qu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, qu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (qu *QrcodeUpdate) SaveX(ctx context.Context) int {
	affected, err := qu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (qu *QrcodeUpdate) Exec(ctx context.Context) error {
	_, err := qu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qu *QrcodeUpdate) ExecX(ctx context.Context) {
	if err := qu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qu *QrcodeUpdate) check() error {
	if _, ok := qu.mutation.UserID(); qu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Qrcode.user"`)
	}
	return nil
}

func (qu *QrcodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   qrcode.Table,
			Columns: qrcode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: qrcode.FieldID,
			},
		},
	}
	if ps := qu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := qu.mutation.QrcodeID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldQrcodeID,
		})
	}
	if value, ok := qu.mutation.OrderID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldOrderID,
		})
	}
	if value, ok := qu.mutation.OrderStatus(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldOrderStatus,
		})
	}
	if value, ok := qu.mutation.BranchName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldBranchName,
		})
	}
	if value, ok := qu.mutation.OrderChannel(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldOrderChannel,
		})
	}
	if value, ok := qu.mutation.TotalPaid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: qrcode.FieldTotalPaid,
		})
	}
	if value, ok := qu.mutation.AddedTotalPaid(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: qrcode.FieldTotalPaid,
		})
	}
	if qu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qrcode.UserTable,
			Columns: []string{qrcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := qu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qrcode.UserTable,
			Columns: []string{qrcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, qu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{qrcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// QrcodeUpdateOne is the builder for updating a single Qrcode entity.
type QrcodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QrcodeMutation
}

// SetQrcodeID sets the "qrcode_id" field.
func (quo *QrcodeUpdateOne) SetQrcodeID(s string) *QrcodeUpdateOne {
	quo.mutation.SetQrcodeID(s)
	return quo
}

// SetOrderID sets the "order_id" field.
func (quo *QrcodeUpdateOne) SetOrderID(s string) *QrcodeUpdateOne {
	quo.mutation.SetOrderID(s)
	return quo
}

// SetOrderStatus sets the "order_status" field.
func (quo *QrcodeUpdateOne) SetOrderStatus(s string) *QrcodeUpdateOne {
	quo.mutation.SetOrderStatus(s)
	return quo
}

// SetBranchName sets the "branch_name" field.
func (quo *QrcodeUpdateOne) SetBranchName(s string) *QrcodeUpdateOne {
	quo.mutation.SetBranchName(s)
	return quo
}

// SetOrderChannel sets the "order_channel" field.
func (quo *QrcodeUpdateOne) SetOrderChannel(s string) *QrcodeUpdateOne {
	quo.mutation.SetOrderChannel(s)
	return quo
}

// SetTotalPaid sets the "total_paid" field.
func (quo *QrcodeUpdateOne) SetTotalPaid(i int) *QrcodeUpdateOne {
	quo.mutation.ResetTotalPaid()
	quo.mutation.SetTotalPaid(i)
	return quo
}

// AddTotalPaid adds i to the "total_paid" field.
func (quo *QrcodeUpdateOne) AddTotalPaid(i int) *QrcodeUpdateOne {
	quo.mutation.AddTotalPaid(i)
	return quo
}

// SetUserID sets the "user_id" field.
func (quo *QrcodeUpdateOne) SetUserID(i int) *QrcodeUpdateOne {
	quo.mutation.SetUserID(i)
	return quo
}

// SetUser sets the "user" edge to the User entity.
func (quo *QrcodeUpdateOne) SetUser(u *User) *QrcodeUpdateOne {
	return quo.SetUserID(u.ID)
}

// Mutation returns the QrcodeMutation object of the builder.
func (quo *QrcodeUpdateOne) Mutation() *QrcodeMutation {
	return quo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (quo *QrcodeUpdateOne) ClearUser() *QrcodeUpdateOne {
	quo.mutation.ClearUser()
	return quo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (quo *QrcodeUpdateOne) Select(field string, fields ...string) *QrcodeUpdateOne {
	quo.fields = append([]string{field}, fields...)
	return quo
}

// Save executes the query and returns the updated Qrcode entity.
func (quo *QrcodeUpdateOne) Save(ctx context.Context) (*Qrcode, error) {
	var (
		err  error
		node *Qrcode
	)
	if len(quo.hooks) == 0 {
		if err = quo.check(); err != nil {
			return nil, err
		}
		node, err = quo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QrcodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = quo.check(); err != nil {
				return nil, err
			}
			quo.mutation = mutation
			node, err = quo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(quo.hooks) - 1; i >= 0; i-- {
			if quo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = quo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, quo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Qrcode)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from QrcodeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (quo *QrcodeUpdateOne) SaveX(ctx context.Context) *Qrcode {
	node, err := quo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (quo *QrcodeUpdateOne) Exec(ctx context.Context) error {
	_, err := quo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (quo *QrcodeUpdateOne) ExecX(ctx context.Context) {
	if err := quo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (quo *QrcodeUpdateOne) check() error {
	if _, ok := quo.mutation.UserID(); quo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Qrcode.user"`)
	}
	return nil
}

func (quo *QrcodeUpdateOne) sqlSave(ctx context.Context) (_node *Qrcode, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   qrcode.Table,
			Columns: qrcode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: qrcode.FieldID,
			},
		},
	}
	id, ok := quo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Qrcode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := quo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, qrcode.FieldID)
		for _, f := range fields {
			if !qrcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != qrcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := quo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := quo.mutation.QrcodeID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldQrcodeID,
		})
	}
	if value, ok := quo.mutation.OrderID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldOrderID,
		})
	}
	if value, ok := quo.mutation.OrderStatus(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldOrderStatus,
		})
	}
	if value, ok := quo.mutation.BranchName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldBranchName,
		})
	}
	if value, ok := quo.mutation.OrderChannel(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldOrderChannel,
		})
	}
	if value, ok := quo.mutation.TotalPaid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: qrcode.FieldTotalPaid,
		})
	}
	if value, ok := quo.mutation.AddedTotalPaid(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: qrcode.FieldTotalPaid,
		})
	}
	if quo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qrcode.UserTable,
			Columns: []string{qrcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := quo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qrcode.UserTable,
			Columns: []string{qrcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Qrcode{config: quo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, quo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{qrcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
