// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aramen-api/cmd/api/ent/qrcode"
	"aramen-api/cmd/api/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QrcodeCreate is the builder for creating a Qrcode entity.
type QrcodeCreate struct {
	config
	mutation *QrcodeMutation
	hooks    []Hook
}

// SetQrcodeID sets the "qrcode_id" field.
func (qc *QrcodeCreate) SetQrcodeID(s string) *QrcodeCreate {
	qc.mutation.SetQrcodeID(s)
	return qc
}

// SetOrderID sets the "order_id" field.
func (qc *QrcodeCreate) SetOrderID(s string) *QrcodeCreate {
	qc.mutation.SetOrderID(s)
	return qc
}

// SetOrderStatus sets the "order_status" field.
func (qc *QrcodeCreate) SetOrderStatus(s string) *QrcodeCreate {
	qc.mutation.SetOrderStatus(s)
	return qc
}

// SetBranchName sets the "branch_name" field.
func (qc *QrcodeCreate) SetBranchName(s string) *QrcodeCreate {
	qc.mutation.SetBranchName(s)
	return qc
}

// SetOrderChannel sets the "order_channel" field.
func (qc *QrcodeCreate) SetOrderChannel(s string) *QrcodeCreate {
	qc.mutation.SetOrderChannel(s)
	return qc
}

// SetTotalPaid sets the "total_paid" field.
func (qc *QrcodeCreate) SetTotalPaid(i int) *QrcodeCreate {
	qc.mutation.SetTotalPaid(i)
	return qc
}

// SetUserID sets the "user_id" field.
func (qc *QrcodeCreate) SetUserID(i int) *QrcodeCreate {
	qc.mutation.SetUserID(i)
	return qc
}

// SetUser sets the "user" edge to the User entity.
func (qc *QrcodeCreate) SetUser(u *User) *QrcodeCreate {
	return qc.SetUserID(u.ID)
}

// Mutation returns the QrcodeMutation object of the builder.
func (qc *QrcodeCreate) Mutation() *QrcodeMutation {
	return qc.mutation
}

// Save creates the Qrcode in the database.
func (qc *QrcodeCreate) Save(ctx context.Context) (*Qrcode, error) {
	var (
		err  error
		node *Qrcode
	)
	if len(qc.hooks) == 0 {
		if err = qc.check(); err != nil {
			return nil, err
		}
		node, err = qc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*QrcodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = qc.check(); err != nil {
				return nil, err
			}
			qc.mutation = mutation
			if node, err = qc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(qc.hooks) - 1; i >= 0; i-- {
			if qc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = qc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, qc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Qrcode)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from QrcodeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (qc *QrcodeCreate) SaveX(ctx context.Context) *Qrcode {
	v, err := qc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qc *QrcodeCreate) Exec(ctx context.Context) error {
	_, err := qc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qc *QrcodeCreate) ExecX(ctx context.Context) {
	if err := qc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qc *QrcodeCreate) check() error {
	if _, ok := qc.mutation.QrcodeID(); !ok {
		return &ValidationError{Name: "qrcode_id", err: errors.New(`ent: missing required field "Qrcode.qrcode_id"`)}
	}
	if _, ok := qc.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "Qrcode.order_id"`)}
	}
	if _, ok := qc.mutation.OrderStatus(); !ok {
		return &ValidationError{Name: "order_status", err: errors.New(`ent: missing required field "Qrcode.order_status"`)}
	}
	if _, ok := qc.mutation.BranchName(); !ok {
		return &ValidationError{Name: "branch_name", err: errors.New(`ent: missing required field "Qrcode.branch_name"`)}
	}
	if _, ok := qc.mutation.OrderChannel(); !ok {
		return &ValidationError{Name: "order_channel", err: errors.New(`ent: missing required field "Qrcode.order_channel"`)}
	}
	if _, ok := qc.mutation.TotalPaid(); !ok {
		return &ValidationError{Name: "total_paid", err: errors.New(`ent: missing required field "Qrcode.total_paid"`)}
	}
	if _, ok := qc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Qrcode.user_id"`)}
	}
	if _, ok := qc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Qrcode.user"`)}
	}
	return nil
}

func (qc *QrcodeCreate) sqlSave(ctx context.Context) (*Qrcode, error) {
	_node, _spec := qc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (qc *QrcodeCreate) createSpec() (*Qrcode, *sqlgraph.CreateSpec) {
	var (
		_node = &Qrcode{config: qc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: qrcode.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: qrcode.FieldID,
			},
		}
	)
	if value, ok := qc.mutation.QrcodeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldQrcodeID,
		})
		_node.QrcodeID = value
	}
	if value, ok := qc.mutation.OrderID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldOrderID,
		})
		_node.OrderID = value
	}
	if value, ok := qc.mutation.OrderStatus(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldOrderStatus,
		})
		_node.OrderStatus = value
	}
	if value, ok := qc.mutation.BranchName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldBranchName,
		})
		_node.BranchName = value
	}
	if value, ok := qc.mutation.OrderChannel(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: qrcode.FieldOrderChannel,
		})
		_node.OrderChannel = value
	}
	if value, ok := qc.mutation.TotalPaid(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: qrcode.FieldTotalPaid,
		})
		_node.TotalPaid = value
	}
	if nodes := qc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   qrcode.UserTable,
			Columns: []string{qrcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QrcodeCreateBulk is the builder for creating many Qrcode entities in bulk.
type QrcodeCreateBulk struct {
	config
	builders []*QrcodeCreate
}

// Save creates the Qrcode entities in the database.
func (qcb *QrcodeCreateBulk) Save(ctx context.Context) ([]*Qrcode, error) {
	specs := make([]*sqlgraph.CreateSpec, len(qcb.builders))
	nodes := make([]*Qrcode, len(qcb.builders))
	mutators := make([]Mutator, len(qcb.builders))
	for i := range qcb.builders {
		func(i int, root context.Context) {
			builder := qcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QrcodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qcb *QrcodeCreateBulk) SaveX(ctx context.Context) []*Qrcode {
	v, err := qcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qcb *QrcodeCreateBulk) Exec(ctx context.Context) error {
	_, err := qcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qcb *QrcodeCreateBulk) ExecX(ctx context.Context) {
	if err := qcb.Exec(ctx); err != nil {
		panic(err)
	}
}
