// Code generated by ent, DO NOT EDIT.

package ent

import (
	"aramen-api/cmd/api/ent/predicate"
	"aramen-api/cmd/api/ent/user"
	"aramen-api/cmd/api/ent/userotp"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserOtpQuery is the builder for querying UserOtp entities.
type UserOtpQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserOtp
	withUser   *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserOtpQuery builder.
func (uoq *UserOtpQuery) Where(ps ...predicate.UserOtp) *UserOtpQuery {
	uoq.predicates = append(uoq.predicates, ps...)
	return uoq
}

// Limit adds a limit step to the query.
func (uoq *UserOtpQuery) Limit(limit int) *UserOtpQuery {
	uoq.limit = &limit
	return uoq
}

// Offset adds an offset step to the query.
func (uoq *UserOtpQuery) Offset(offset int) *UserOtpQuery {
	uoq.offset = &offset
	return uoq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uoq *UserOtpQuery) Unique(unique bool) *UserOtpQuery {
	uoq.unique = &unique
	return uoq
}

// Order adds an order step to the query.
func (uoq *UserOtpQuery) Order(o ...OrderFunc) *UserOtpQuery {
	uoq.order = append(uoq.order, o...)
	return uoq
}

// QueryUser chains the current query on the "user" edge.
func (uoq *UserOtpQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: uoq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uoq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uoq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userotp.Table, userotp.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, userotp.UserTable, userotp.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(uoq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserOtp entity from the query.
// Returns a *NotFoundError when no UserOtp was found.
func (uoq *UserOtpQuery) First(ctx context.Context) (*UserOtp, error) {
	nodes, err := uoq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userotp.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uoq *UserOtpQuery) FirstX(ctx context.Context) *UserOtp {
	node, err := uoq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserOtp ID from the query.
// Returns a *NotFoundError when no UserOtp ID was found.
func (uoq *UserOtpQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uoq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userotp.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uoq *UserOtpQuery) FirstIDX(ctx context.Context) int {
	id, err := uoq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserOtp entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserOtp entity is found.
// Returns a *NotFoundError when no UserOtp entities are found.
func (uoq *UserOtpQuery) Only(ctx context.Context) (*UserOtp, error) {
	nodes, err := uoq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userotp.Label}
	default:
		return nil, &NotSingularError{userotp.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uoq *UserOtpQuery) OnlyX(ctx context.Context) *UserOtp {
	node, err := uoq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserOtp ID in the query.
// Returns a *NotSingularError when more than one UserOtp ID is found.
// Returns a *NotFoundError when no entities are found.
func (uoq *UserOtpQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uoq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userotp.Label}
	default:
		err = &NotSingularError{userotp.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uoq *UserOtpQuery) OnlyIDX(ctx context.Context) int {
	id, err := uoq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserOtps.
func (uoq *UserOtpQuery) All(ctx context.Context) ([]*UserOtp, error) {
	if err := uoq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uoq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uoq *UserOtpQuery) AllX(ctx context.Context) []*UserOtp {
	nodes, err := uoq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserOtp IDs.
func (uoq *UserOtpQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := uoq.Select(userotp.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uoq *UserOtpQuery) IDsX(ctx context.Context) []int {
	ids, err := uoq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uoq *UserOtpQuery) Count(ctx context.Context) (int, error) {
	if err := uoq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uoq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uoq *UserOtpQuery) CountX(ctx context.Context) int {
	count, err := uoq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uoq *UserOtpQuery) Exist(ctx context.Context) (bool, error) {
	if err := uoq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uoq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uoq *UserOtpQuery) ExistX(ctx context.Context) bool {
	exist, err := uoq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserOtpQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uoq *UserOtpQuery) Clone() *UserOtpQuery {
	if uoq == nil {
		return nil
	}
	return &UserOtpQuery{
		config:     uoq.config,
		limit:      uoq.limit,
		offset:     uoq.offset,
		order:      append([]OrderFunc{}, uoq.order...),
		predicates: append([]predicate.UserOtp{}, uoq.predicates...),
		withUser:   uoq.withUser.Clone(),
		// clone intermediate query.
		sql:    uoq.sql.Clone(),
		path:   uoq.path,
		unique: uoq.unique,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (uoq *UserOtpQuery) WithUser(opts ...func(*UserQuery)) *UserOtpQuery {
	query := &UserQuery{config: uoq.config}
	for _, opt := range opts {
		opt(query)
	}
	uoq.withUser = query
	return uoq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserOtp.Query().
//		GroupBy(userotp.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uoq *UserOtpQuery) GroupBy(field string, fields ...string) *UserOtpGroupBy {
	grbuild := &UserOtpGroupBy{config: uoq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uoq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uoq.sqlQuery(ctx), nil
	}
	grbuild.label = userotp.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.UserOtp.Query().
//		Select(userotp.FieldUserID).
//		Scan(ctx, &v)
//
func (uoq *UserOtpQuery) Select(fields ...string) *UserOtpSelect {
	uoq.fields = append(uoq.fields, fields...)
	selbuild := &UserOtpSelect{UserOtpQuery: uoq}
	selbuild.label = userotp.Label
	selbuild.flds, selbuild.scan = &uoq.fields, selbuild.Scan
	return selbuild
}

func (uoq *UserOtpQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uoq.fields {
		if !userotp.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uoq.path != nil {
		prev, err := uoq.path(ctx)
		if err != nil {
			return err
		}
		uoq.sql = prev
	}
	return nil
}

func (uoq *UserOtpQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserOtp, error) {
	var (
		nodes       = []*UserOtp{}
		_spec       = uoq.querySpec()
		loadedTypes = [1]bool{
			uoq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserOtp).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserOtp{config: uoq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uoq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := uoq.withUser; query != nil {
		if err := uoq.loadUser(ctx, query, nodes, nil,
			func(n *UserOtp, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uoq *UserOtpQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserOtp, init func(*UserOtp), assign func(*UserOtp, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UserOtp)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (uoq *UserOtpQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uoq.querySpec()
	_spec.Node.Columns = uoq.fields
	if len(uoq.fields) > 0 {
		_spec.Unique = uoq.unique != nil && *uoq.unique
	}
	return sqlgraph.CountNodes(ctx, uoq.driver, _spec)
}

func (uoq *UserOtpQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := uoq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (uoq *UserOtpQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userotp.Table,
			Columns: userotp.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userotp.FieldID,
			},
		},
		From:   uoq.sql,
		Unique: true,
	}
	if unique := uoq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uoq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userotp.FieldID)
		for i := range fields {
			if fields[i] != userotp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uoq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uoq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uoq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uoq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uoq *UserOtpQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uoq.driver.Dialect())
	t1 := builder.Table(userotp.Table)
	columns := uoq.fields
	if len(columns) == 0 {
		columns = userotp.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uoq.sql != nil {
		selector = uoq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uoq.unique != nil && *uoq.unique {
		selector.Distinct()
	}
	for _, p := range uoq.predicates {
		p(selector)
	}
	for _, p := range uoq.order {
		p(selector)
	}
	if offset := uoq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uoq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserOtpGroupBy is the group-by builder for UserOtp entities.
type UserOtpGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uogb *UserOtpGroupBy) Aggregate(fns ...AggregateFunc) *UserOtpGroupBy {
	uogb.fns = append(uogb.fns, fns...)
	return uogb
}

// Scan applies the group-by query and scans the result into the given value.
func (uogb *UserOtpGroupBy) Scan(ctx context.Context, v any) error {
	query, err := uogb.path(ctx)
	if err != nil {
		return err
	}
	uogb.sql = query
	return uogb.sqlScan(ctx, v)
}

func (uogb *UserOtpGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range uogb.fields {
		if !userotp.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uogb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uogb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uogb *UserOtpGroupBy) sqlQuery() *sql.Selector {
	selector := uogb.sql.Select()
	aggregation := make([]string, 0, len(uogb.fns))
	for _, fn := range uogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(uogb.fields)+len(uogb.fns))
		for _, f := range uogb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(uogb.fields...)...)
}

// UserOtpSelect is the builder for selecting fields of UserOtp entities.
type UserOtpSelect struct {
	*UserOtpQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uos *UserOtpSelect) Scan(ctx context.Context, v any) error {
	if err := uos.prepareQuery(ctx); err != nil {
		return err
	}
	uos.sql = uos.UserOtpQuery.sqlQuery(ctx)
	return uos.sqlScan(ctx, v)
}

func (uos *UserOtpSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := uos.sql.Query()
	if err := uos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
