// Code generated by ent, DO NOT EDIT.

package branches

const (
	// Label holds the string label denoting the branches type in the database.
	Label = "branches"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldShortDescription holds the string denoting the short_description field in the database.
	FieldShortDescription = "short_description"
	// FieldFullDescription holds the string denoting the full_description field in the database.
	FieldFullDescription = "full_description"
	// FieldTelephone holds the string denoting the telephone field in the database.
	FieldTelephone = "telephone"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// FieldGooleMapURL holds the string denoting the goole_map_url field in the database.
	FieldGooleMapURL = "goole_map_url"
	// FieldDineIn holds the string denoting the dine_in field in the database.
	FieldDineIn = "dine_in"
	// FieldDelivery holds the string denoting the delivery field in the database.
	FieldDelivery = "delivery"
	// FieldTakeAway holds the string denoting the take_away field in the database.
	FieldTakeAway = "take_away"
	// Table holds the table name of the branches in the database.
	Table = "branches"
)

// Columns holds all SQL columns for branches fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldShortDescription,
	FieldFullDescription,
	FieldTelephone,
	FieldLatitude,
	FieldLongitude,
	FieldGooleMapURL,
	FieldDineIn,
	FieldDelivery,
	FieldTakeAway,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
